#Encoding of the categorical variables

#One hot encoding

In [1]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [2]:
x = np.array([['A'],['A'],['B'], ['c']])
x

array([['A'],
       ['A'],
       ['B'],
       ['c']], dtype='<U1')

In [3]:
enc = OneHotEncoder()

In [4]:
enc.fit_transform(x).toarray()


array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
enc = OneHotEncoder(sparse=False )
enc.fit_transform(x)

c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
enc = OneHotEncoder()
enc.fit_transform(x).todense()

matrix([[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Removing one dummy variable

In [7]:
x = np.array([['A'],['A'],['B'], ['c']])


In [8]:
x = np.array([['A'],['B'],['A'],['B'], ['B'], ['C']])
x


array([['A'],
       ['B'],
       ['A'],
       ['B'],
       ['B'],
       ['C']], dtype='<U1')

In [9]:
enc = OneHotEncoder(drop='first')
enc.fit_transform(x).toarray()

array([[0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [10]:
x = np.array([['A'],['A'],['A'],['B'],['c']])
enc = OneHotEncoder(sparse=False ,drop='if_binary')
enc.fit_transform(x)


c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
enc = OneHotEncoder(sparse=False, handle_unknown='ignore')
enc.fit(x)

c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(handle_unknown='ignore', sparse=False, sparse_output=False)

In [12]:
enc.transform(x)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
y= [['A', ['A'], ['B'], ['C']]]
enc = OneHotEncoder(sparse=False ,handle_unknown ='ignore')
enc.fit(x)
enc.transform(x)

c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
enc = OneHotEncoder(sparse=False ,handle_unknown='ignore')
enc.fit(x)


c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(handle_unknown='ignore', sparse=False, sparse_output=False)

In [15]:
enc.transform(x)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
x =[['A','X'],['B','Y'],['C','Z']]

In [17]:
Enc = OneHotEncoder(sparse=False ,categories=[['A','B','C','D'],['X','Y','Z']])
Enc.fit_transform(x)# fit the encoder and transform the data

c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 1.]])

In [18]:
Y = [['D','Z']]
Enc.transform(Y) # transform the new data

array([[0., 0., 0., 1., 0., 0., 1.]])

Ordinal Encoding


In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
x = [['High'], ['Low'], ['Medium'], ['Low']]

In [21]:
ord_enc = OrdinalEncoder()
ord_enc.fit_transform(x)

array([[0.],
       [1.],
       [2.],
       [1.]])

We want 
!1)low ==0
2}medium ==1
high==2

In [22]:
enc = OrdinalEncoder(categories=[['Low', 'Medium', 'High']])
enc.fit_transform(x)

array([[2.],
       [0.],
       [1.],
       [0.]])

In [23]:
x = [['A', 'High'], ['B', 'Low'], ['C', 'Medium'], ['D', 'High']]
enc = OrdinalEncoder(categories=[['A', 'B', 'C', 'D'], ['Low', 'Medium', 'High']], handle_unknown='use_encoded_value', unknown_value=-1)
enc.fit_transform(x)

array([[0., 2.],
       [1., 0.],
       [2., 1.],
       [3., 2.]])

In [24]:
from sklearn.preprocessing import LabelEncoder
x = ['A', 'B', 'C', 'D', 'A', 'B']
le = LabelEncoder()
le.fit_transform(x)

array([0, 1, 2, 3, 0, 1], dtype=int64)

Exercise 1


In [25]:
from sklearn.preprocessing import OneHotEncoder
x = [['x','High'], ['y','Low'], ['z','Medium'], ['w','High']]
enc = OneHotEncoder(sparse=False, handle_unknown='ignore')
enc.fit_transform(x)


c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0.]])

In [26]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.compose import ColumnTransformer
x = [['x','High'], ['y','Low'], ['z','Medium'], ['w','High']]
column_transform = ColumnTransformer(transformers=[
    ('onehot', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), [0]),   # column 0
    ('ordinal', OrdinalEncoder(categories=[['High', 'Medium', 'Low']]), [1])        # column 1
])

# Transform the data
encoded = column_transform.fit_transform(x)
encoded


array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 2.],
       [0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 0.]])

In [56]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
# Sample dataset
df = pd.DataFrame({
    'Color': ['Red', 'Green', 'Blue', 'Green','Green'],
    'Size': ['S', 'S', 'L', 'S', 'S']
})

print(df)
df1 = df.copy()
df2 = df.copy()

   Color Size
0    Red    S
1  Green    S
2   Blue    L
3  Green    S
4  Green    S


In [57]:
encoding = OneHotEncoder()
encoding.fit_transform(df[['Color','Size']]).toarray()


array([[0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1.]])

In [58]:
encoding = OneHotEncoder(drop='first')
encoding.fit_transform(df[['Color','Size']]).toarray()

array([[0., 1., 1.],
       [1., 0., 1.],
       [0., 0., 0.],
       [1., 0., 1.],
       [1., 0., 1.]])

In [59]:
onehot = OneHotEncoder(drop ='if_binary')
onehot.fit_transform(df2[['Color','Size']]).toarray()

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.]])

In [72]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
import pandas as pd

# Sample data
df = pd.DataFrame({'Size': ['Small', 'Medium', 'Large', 'Small', 'Large'],
                  'color': ['Red', 'Green', 'Blue', 'Green','Green']})

# Define transformer — using only OrdinalEncoder here because we only have one column
column_trans = ColumnTransformer(
    transformers=[
        ('ordinal', OrdinalEncoder(categories=[['Small', 'Medium', 'Large']]), ['Size']),
        ('onehot', OneHotEncoder(sparse_output =False, handle_unknown='ignore'), ['color'])
    ],
    remainder='passthrough'
)

# Apply transformation
encoded = column_trans.fit_transform(df)



print(encoded)


[[0. 0. 0. 1.]
 [1. 0. 1. 0.]
 [2. 1. 0. 0.]
 [0. 0. 1. 0.]
 [2. 0. 1. 0.]]


In [80]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import pandas as pd
df = pd.DataFrame({
    'Color': ['Red', 'Green', 'Blue', 'Green','Green'],
    'Size': ['S', 'S', 'L', 'S', 'S']
})
label = LabelEncoder()
df['Color_'] = label.fit_transform(df['Color' ])
df['size_'] = label.fit_transform(df['Size' ])
df

,Color,Size,Color_,size_
0,Red,S,2,1
1,Green,S,1,1
2,Blue,L,0,0
3,Green,S,1,1
4,Green,S,1,1
