#Encoding of the categorical variables

#One hot encoding

In [30]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [31]:
x = np.array([['A'],['A'],['B'], ['c']])
x

array([['A'],
       ['A'],
       ['B'],
       ['c']], dtype='<U1')

In [32]:
enc = OneHotEncoder()

In [33]:
enc.fit_transform(x).toarray()


array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
enc = OneHotEncoder(sparse=False )
enc.fit_transform(x)

c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
enc = OneHotEncoder()
enc.fit_transform(x).todense()

matrix([[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Removing one dummy variable

In [39]:
x
enc = OneHotEncoder(drop='first') 
enc.fit_transform(x).toarray()

array([[0.],
       [0.],
       [0.],
       [1.]])

In [51]:
x = np.array([['A'],['B'],['A'],['B'], ['B'], ['C']])
x


array([['A'],
       ['B'],
       ['A'],
       ['B'],
       ['B'],
       ['C']], dtype='<U1')

In [52]:
enc = OneHotEncoder(drop='first')
enc.fit_transform(x).toarray()

array([[0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.]])