#Encoding of the categorical variables

#One hot encoding

In [51]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [52]:
x = np.array([['A'],['A'],['B'], ['c']])
x

array([['A'],
       ['A'],
       ['B'],
       ['c']], dtype='<U1')

In [53]:
enc = OneHotEncoder()

In [54]:
enc.fit_transform(x).toarray()


array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
enc = OneHotEncoder(sparse=False )
enc.fit_transform(x)

c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
enc = OneHotEncoder()
enc.fit_transform(x).todense()

matrix([[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Removing one dummy variable

In [57]:
x = np.array([['A'],['A'],['B'], ['c']])


In [58]:
x = np.array([['A'],['B'],['A'],['B'], ['B'], ['C']])
x


array([['A'],
       ['B'],
       ['A'],
       ['B'],
       ['B'],
       ['C']], dtype='<U1')

In [59]:
enc = OneHotEncoder(drop='first')
enc.fit_transform(x).toarray()

array([[0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [60]:
x = np.array([['A'],['A'],['A'],['B'],['c']])
enc = OneHotEncoder(sparse=False ,drop='if_binary')
enc.fit_transform(x)


c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
enc = OneHotEncoder(sparse=False, handle_unknown='ignore')
enc.fit(x)

c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(handle_unknown='ignore', sparse=False, sparse_output=False)

In [62]:
enc.transform(x)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
y= [['A', ['A'], ['B'], ['C']]]
enc = OneHotEncoder(sparse=False ,handle_unknown ='ignore')
enc.fit(x)
enc.transform(x)

c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
enc = OneHotEncoder(sparse=False ,handle_unknown='ignore')
enc.fit(x)


c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(handle_unknown='ignore', sparse=False, sparse_output=False)

In [ ]:
enc.transform(x)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
x =[['A','X'],['B','Y'],['C','Z']]

In [68]:
Enc = OneHotEncoder(sparse=False ,categories=[['A','B','C','D'],['X','Y','Z']])
Enc.fit_transform(x)# fit the encoder and transform the data

c:\Users\Cheru\anaconda3\ana\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 1.]])

In [69]:
Y = [['D','Z']]
Enc.transform(Y) # transform the new data

array([[0., 0., 0., 1., 0., 0., 1.]])