# Scaling

Scaling is a data processing refers totransforming numerical features where it fall within a similar range.

In [27]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [28]:
df =  pd.read_csv ('sample_dataset.csv').iloc[:, 0 : 3].dropna()
df

,mean radius,mean texture,mean perimeter
1,20.57,17.77,132.90
2,19.69,21.25,130.00
3,11.42,20.38,77.58
5,12.45,15.70,82.57
7,13.71,20.83,90.20
...,...,...,...
562,15.22,30.62,103.40
563,20.92,25.09,143.00
564,21.56,22.39,142.00
566,16.60,28.08,108.30


## Normalization

0 - 1 scaling

In [29]:
SCALER = MinMaxScaler()
x_scaled = SCALER.fit_transform(df)
x_scaled

array([[0.63004759, 0.27257355, 0.60432679],
       [0.58687012, 0.3902604 , 0.58368915],
       [0.18110004, 0.36083869, 0.21064617],
       ...,
       [0.67862225, 0.42881299, 0.66908625],
       [0.43525833, 0.62123774, 0.42926274],
       [0.63151955, 0.66351031, 0.65556504]])

In [31]:
np.apply_over_axes(np.max,x_scaled,0)



array([[1., 1., 1.]])

In [ ]:
np.apply_over_axes(np.max,x_scaled, 0)


array([[1., 1., 1.]])

In [ ]:
np.apply_over_axes(np.min,x_scaled, 0)


array([[0., 0., 0.]])

## Standard Scaler

In [32]:
from sklearn.preprocessing import StandardScaler

In [34]:
df

,mean radius,mean texture,mean perimeter
1,20.57,17.77,132.90
2,19.69,21.25,130.00
3,11.42,20.38,77.58
5,12.45,15.70,82.57
7,13.71,20.83,90.20
...,...,...,...
562,15.22,30.62,103.40
563,20.92,25.09,143.00
564,21.56,22.39,142.00
566,16.60,28.08,108.30


In [42]:

SCALE = StandardScaler()
x_scale = SCALER.fit_transform(df)
x_scale

array([[0.63004759, 0.27257355, 0.60432679],
       [0.58687012, 0.3902604 , 0.58368915],
       [0.18110004, 0.36083869, 0.21064617],
       ...,
       [0.67862225, 0.42881299, 0.66908625],
       [0.43525833, 0.62123774, 0.42926274],
       [0.63151955, 0.66351031, 0.65556504]])

In [ ]:
print(np.var(x_scaled, axis=0))
print(x_scaled.shape)
np.apply_over_axes(np.max,x_scaled,0 )

np.apply_over_axes(np.mean,x_scale,0)






[0.02870215 0.0214786  0.02870028]
(385, 3)


array([[0.31298427, 0.32464107, 0.3120543 ]])

In [48]:
np.apply_over_axes(np.var,x_scale,0)

array([[0.02870215, 0.0214786 , 0.02870028]])

In [49]:
np.apply_over_axes(np.var, x_scale, 0)


array([[0.02870215, 0.0214786 , 0.02870028]])

In [51]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(df)


In [52]:
print("Scaled Data:\n", x_scaled)
print("Variance (axis=0):", np.var(x_scaled, axis=0))
print("Variance using apply_over_axes:", np.apply_over_axes(np.var, x_scaled, 0))

Scaled Data:
 [[ 1.87149535 -0.35527432  1.7252216 ]
 [ 1.61663638  0.44774298  1.6034021 ]
 [-0.77845877  0.24698866 -0.59859036]
 ...
 [ 2.1582117   0.71080038  2.10748279]
 [ 0.72173384  2.02377982  0.6918562 ]
 [ 1.88018373  2.31221994  2.02767001]]
Variance (axis=0): [1. 1. 1.]
Variance using apply_over_axes: [[1. 1. 1.]]
