# Scaling

Scaling is a data processing refers totransforming numerical features where it fall within a similar range.

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [3]:
df =  pd.read_csv ('sample_dataset.csv').iloc[:, 0 : 3].dropna()
df

,mean radius,mean texture,mean perimeter
1,20.57,17.77,132.90
2,19.69,21.25,130.00
3,11.42,20.38,77.58
5,12.45,15.70,82.57
7,13.71,20.83,90.20
...,...,...,...
562,15.22,30.62,103.40
563,20.92,25.09,143.00
564,21.56,22.39,142.00
566,16.60,28.08,108.30


## Normalization

0 - 1 scaling

In [5]:
SCALER = MinMaxScaler()
x_scaled = SCALER.fit_transform(df)
x_scaled

array([[0.63004759, 0.27257355, 0.60432679],
       [0.58687012, 0.3902604 , 0.58368915],
       [0.18110004, 0.36083869, 0.21064617],
       ...,
       [0.67862225, 0.42881299, 0.66908625],
       [0.43525833, 0.62123774, 0.42926274],
       [0.63151955, 0.66351031, 0.65556504]])

In [ ]:
np.apply_over_axes(np.max,0, x_scaled)



SyntaxError: invalid syntax (759669981.py, line 2)

In [23]:
np.apply_over_axes(np.max,x_scaled, 0)


array([[1., 1., 1.]])

In [26]:
np.apply_over_axes(np.min,x_scaled, 0)


array([[0., 0., 0.]])