Pipelines are sequence of transformation that are applied one after another

In [2]:
import numpy as np
from sklearn.preprocessing import PowerTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.impute import SimpleImputer


In [3]:
df = [[1],[2],[3],[np.nan]]
x = SimpleImputer()
y = PowerTransformer()
df_cleaned = SimpleImputer().fit_transform(df)
df_tranformed = PowerTransformer().fit_transform(df_cleaned)
df_tranformed

array([[-1.43683573],
       [ 0.02299615],
       [ 1.39084343],
       [ 0.02299615]])

In [4]:
df = [[1],[2],[3],[np.nan]]
pipe_line = make_pipeline(SimpleImputer(), PowerTransformer())
df_trans = pipe_line.fit_transform(df)
df_trans

array([[-1.43683573],
       [ 0.02299615],
       [ 1.39084343],
       [ 0.02299615]])

In [5]:
pipe = Pipeline([
    ('CLEAN', SimpleImputer()),
    ("power", PowerTransformer())
])

In [6]:
pipe.fit_transform(df)

array([[-1.43683573],
       [ 0.02299615],
       [ 1.39084343],
       [ 0.02299615]])

In [8]:
pipe.set_params(CLEAN__strategy = 'median')

Pipeline(steps=[('CLEAN', SimpleImputer(strategy='median')),
                ('power', PowerTransformer())])

In [9]:
pipe.get_params()

{'memory': None,
 'steps': [('CLEAN', SimpleImputer(strategy='median')),
  ('power', PowerTransformer())],
 'verbose': False,
 'CLEAN': SimpleImputer(strategy='median'),
 'power': PowerTransformer(),
 'CLEAN__add_indicator': False,
 'CLEAN__copy': True,
 'CLEAN__fill_value': None,
 'CLEAN__keep_empty_features': False,
 'CLEAN__missing_values': nan,
 'CLEAN__strategy': 'median',
 'power__copy': True,
 'power__method': 'yeo-johnson',
 'power__standardize': True}